'use client';

import { useState } from 'react';

const SUGGESTIONS = [
  { name: 'Diseño Web Básico', price: 300 },
  { name: 'E-commerce Completo', price: 800 },
  { name: 'Mantenimiento Mensual', price: 50 },
  { name: 'Rediseño de Logo', price: 150 },
  { name: 'Consultoría SEO', price: 200 },
];

export default function QuoteDashboard({ onLogout }) {
  // Core Info
  const [clientName, setClientName] = useState('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [packageName, setPackageName] = useState('');
  const [quoteNumber, setQuoteNumber] = useState(Date.now().toString().slice(-6));
  
  // New Fields
  const [currency, setCurrency] = useState('MXN'); // 'USD' or 'MXN'
  const [clientAddress, setClientAddress] = useState('');
  const [clientEmail, setClientEmail] = useState('');
  const [clientPhone, setClientPhone] = useState('');
  const [notes, setNotes] = useState('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');

  // Payment Method State
  const [paymentMethod, setPaymentMethod] = useState('bank'); // 'bank' or 'link'
  const [paymentLink, setPaymentLink] = useState('https://paypal.me/noermorales');
  const [bankDetails, setBankDetails] = useState({
    bank: 'BBVA',
    account: '1234 5678 9012',
    clabe: '012345678901234567',
    holder: 'Noelí Rodríguez'
  });

  // Added Quantity
  const [items, setItems] = useState([{ id: 1, name: '', price: 0, quantity: 1 }]);

  const addItem = () => {
    setItems([...items, { id: Date.now(), name: '', price: 0, quantity: 1 }]);
  };

  const removeItem = (id) => {
    setItems(items.filter(item => item.id !== id));
  };

  const updateItem = (id, field, value) => {
    setItems(items.map(item => 
      item.id === id ? { ...item, [field]: (field === 'price' || field === 'quantity') ? Number(value) : value } : item
    ));
  };

  const addSuggestion = (suggestion) => {
    setItems([...items, { id: Date.now(), ...suggestion, quantity: 1 }]);
  };

  const subtotal = items.reduce((sum, item) => sum + (item.price * item.quantity), 0);
  const total = subtotal; 

  const handlePrint = () => {
    window.print();
  };

  const getFormattedDate = (dateStr) => {
     if (!dateStr) return '';
     const d = new Date(dateStr + 'T12:00:00'); 
     const day = d.getDate();
     const month = d.toLocaleDateString('es-ES', { month: 'long' });
     const year = d.getFullYear();
     return `${day} de ${month} del ${year}`;
  };

  const handleDownloadMarkdown = () => {
    const content = `
# Cotización #${quoteNumber}: ${packageName}

**Para:** ${clientName}
**Fecha:** ${getFormattedDate(date)}
${clientEmail ? `**Email:** ${clientEmail}` : ''}
${clientPhone ? `**Tel:** ${clientPhone}` : ''}

---

## Servicios (${currency})

${items.map(item => `- **${item.name}** (x${item.quantity}): $${(item.price * item.quantity).toFixed(2)}`).join('\n')}

---

**Total:** $${total.toFixed(2)} ${currency}

**Notas:**
${notes}

**Método de Pago:**
${paymentMethod === 'bank' ? `
Banco: ${bankDetails.bank}
Cuenta: ${bankDetails.account}
CLABE: ${bankDetails.clabe}
Titular: ${bankDetails.holder}
` : `Link: ${paymentLink}`}

Generated by noermorales.com
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cotizacion-${quoteNumber}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-white text-black p-8 print:bg-[#F9F9F7] print:text-black print:p-0 font-inter">
      <div className="max-w-6xl mx-auto">
        {/* Editor Header - Hidden in Print */}
        <div className="flex justify-between items-center mb-6 print:hidden">
          <h1 className="text-2xl font-bold text-black tracking-tight">
            Generador de Cotizaciones
          </h1>
          <div className="flex items-center gap-3">
             <select 
              value={currency} 
              onChange={(e) => setCurrency(e.target.value)}
              className="bg-zinc-100 border border-zinc-200 rounded-lg px-3 py-1.5 text-xs focus:outline-none focus:border-black"
            >
              <option value="MXN">MXN ($)</option>
              <option value="USD">USD ($)</option>
            </select>
            <button 
              onClick={onLogout}
              className="text-xs flex items-center gap-2 text-zinc-500 hover:text-black transition-colors"
            >
              Salir
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 print:block">
          {/* Editor Column - Hidden in Print - COMPACT & ROUNDED */}
          <div className="lg:col-span-1 space-y-4 print:hidden">
            
             {/* Payment Method Config */}
             <div className="bg-zinc-50 p-4 rounded-xl border border-zinc-100">
              <h2 className="text-sm font-semibold mb-3">Método de Pago</h2>
              <div className="flex gap-4 mb-3">
                <label className="flex items-center gap-2 text-xs cursor-pointer select-none">
                  <input type="radio" name="paymentType" checked={paymentMethod === 'bank'} onChange={() => setPaymentMethod('bank')} className="accent-black" />
                  Banco
                </label>
                <label className="flex items-center gap-2 text-xs cursor-pointer select-none">
                  <input type="radio" name="paymentType" checked={paymentMethod === 'link'} onChange={() => setPaymentMethod('link')} className="accent-black" />
                  Link de Pago
                </label>
              </div>
              
              {paymentMethod === 'bank' ? (
                <div className="space-y-2">
                   <input type="text" placeholder="Banco" value={bankDetails.bank} onChange={(e) => setBankDetails({...bankDetails, bank: e.target.value})} className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors" />
                   <input type="text" placeholder="No. Cuenta" value={bankDetails.account} onChange={(e) => setBankDetails({...bankDetails, account: e.target.value})} className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors" />
                   <input type="text" placeholder="CLABE" value={bankDetails.clabe} onChange={(e) => setBankDetails({...bankDetails, clabe: e.target.value})} className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors" />
                   <input type="text" placeholder="Titular" value={bankDetails.holder} onChange={(e) => setBankDetails({...bankDetails, holder: e.target.value})} className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors" />
                </div>
              ) : (
                <div>
                   <input type="text" placeholder="Link de pago (ej. paypal.me/...)" value={paymentLink} onChange={(e) => setPaymentLink(e.target.value)} className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors" />
                </div>
              )}
             </div>

            <div className="bg-zinc-50 p-4 rounded-xl border border-zinc-100">
              <h2 className="text-sm font-semibold mb-3">Detalles</h2>
              <div className="space-y-2">
                <div className="grid grid-cols-2 gap-2">
                    <div>
                        <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">No. Cotización</label>
                        <input
                            type="text"
                            value={quoteNumber}
                            onChange={(e) => setQuoteNumber(e.target.value)}
                            className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                        />
                    </div>
                    <div>
                        <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Fecha</label>
                        <input
                            type="date"
                            value={date}
                            onChange={(e) => setDate(e.target.value)}
                            className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                        />
                    </div>
                </div>
                <div>
                  <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Para:</label>
                  <input
                    type="text"
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                  />
                </div>
                 {/* Optional Client Fields */}
                <div>
                   <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Dirección</label>
                   <input
                    type="text"
                    value={clientAddress}
                    onChange={(e) => setClientAddress(e.target.value)}
                    className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                    placeholder="Calle, Ciudad, CP"
                  />
                </div>
                <div className="grid grid-cols-2 gap-2">
                    <div>
                    <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Email</label>
                    <input
                        type="email"
                        value={clientEmail}
                        onChange={(e) => setClientEmail(e.target.value)}
                        className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                    />
                    </div>
                    <div>
                    <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Teléfono</label>
                    <input
                        type="tel"
                        value={clientPhone}
                        onChange={(e) => setClientPhone(e.target.value)}
                        className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                    />
                    </div>
                </div>

                <div>
                  <label className="block text-zinc-500 text-[10px] mb-0.5 uppercase tracking-wide font-medium">Paquete/Proyecto</label>
                  <input
                    type="text"
                    value={packageName}
                    onChange={(e) => setPackageName(e.target.value)}
                    className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                  />
                </div>
              </div>
            </div>

            <div className="bg-zinc-50 p-4 rounded-xl border border-zinc-100">
              <h2 className="text-sm font-semibold mb-3">Servicios</h2>
              <div className="space-y-3">
                {items.map((item, index) => (
                  <div key={item.id} className="flex gap-2 items-start">
                    <div className="flex-1 space-y-1">
                         <input
                          type="text"
                          placeholder="Servicio"
                          value={item.name}
                          onChange={(e) => updateItem(item.id, 'name', e.target.value)}
                          className="w-full bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                        />
                        <div className="flex gap-2">
                             <input
                              type="number"
                              placeholder="Cant."
                              value={item.quantity}
                              onChange={(e) => updateItem(item.id, 'quantity', e.target.value)}
                              className="w-16 bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                            />
                             <input
                              type="number"
                              placeholder="Precio"
                              value={item.price}
                              onChange={(e) => updateItem(item.id, 'price', e.target.value)}
                              className="w-20 bg-white border border-zinc-200 rounded-lg p-1.5 text-xs focus:border-black outline-none transition-colors"
                            />
                        </div>
                    </div>
                   
                    <button 
                      onClick={() => removeItem(item.id)}
                      className="text-zinc-400 hover:text-red-500 p-1.5 transition-colors mt-0.5"
                    >
                      X
                    </button>
                  </div>
                ))}
                
                {/* Suggestions */}
                <div className="flex flex-wrap gap-1.5 pt-2 border-t border-zinc-200">
                    {SUGGESTIONS.map((s, i) => (
                    <button
                        key={i}
                        onClick={() => addSuggestion(s)}
                        className="text-[10px] bg-white border border-zinc-200 hover:border-black text-zinc-600 hover:text-black px-2 py-0.5 rounded-full transition-colors"
                    >
                        + {s.name}
                    </button>
                    ))}
                </div>

                <button
                  onClick={addItem}
                  className="w-full flex items-center justify-center gap-2 text-zinc-600 text-xs hover:bg-zinc-100 py-1.5 border border-dashed border-zinc-300 rounded-lg hover:border-black transition-colors"
                >
                  + Agregar Item
                </button>
              </div>
            </div>

             <div className="bg-zinc-50 p-4 rounded-xl border border-zinc-100">
              <h2 className="text-sm font-semibold mb-3">Notas</h2>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                 className="w-full bg-white border border-zinc-200 rounded-lg p-2 focus:border-black outline-none transition-colors h-24 resize-none text-xs"
                 placeholder="Agregar descripción del proyecto, notas, términos..."
              />
            </div>

            <div className="flex gap-2">
               <button
                onClick={handlePrint}
                className="flex-1 bg-black text-white hover:bg-zinc-800 py-2.5 rounded-lg text-xs font-medium flex items-center justify-center gap-2 transition-colors"
              >
                Imprimir PDF
              </button>
              <button
                onClick={handleDownloadMarkdown}
                className="flex-1 bg-white text-black border border-zinc-200 hover:border-black py-2.5 rounded-lg text-xs font-medium flex items-center justify-center gap-2 transition-colors"
              >
                Descargar MD
              </button>
            </div>
          </div>

          {/* PREVIEW / PRINT VIEW - COMPACT VERSION */}
          <div className="lg:col-span-2 lg:sticky lg:top-6 h-fit">
            <div 
                className="bg-[#F9F9F7] text-[#1a1a1a] shadow-lg min-h-[900px] w-full max-w-[850px] mx-auto print:shadow-none print:w-full print:max-w-none print:h-auto print:min-h-0 relative flex flex-col font-inter print:bg-[#F9F9F7]"
                style={{ WebkitPrintColorAdjust: 'exact', printColorAdjust: 'exact' }}
            >
                
                {/* 1. Header Dark - Compact with Forced Print Color */}
                <div 
                    className="bg-[#2C2C2C] text-white p-8 pr-12 h-36 flex justify-between items-start relative overflow-hidden print:bg-[#2C2C2C]"
                    style={{ WebkitPrintColorAdjust: 'exact', printColorAdjust: 'exact', backgroundColor: '#2C2C2C' }}
                >
                    <div className="z-10">
                        <h1 className="text-4xl font-light tracking-wide mb-1 leading-none text-white print:text-white">Noelí Rodríguez</h1>
                        <p className="text-xs tracking-[0.2em] font-light text-zinc-300 uppercase print:text-zinc-300">Soluciones Digitales</p>
                    </div>
                    {/* Decorative Star/Icon - Smaller */}
                    <div className="text-white opacity-90 text-[60px] leading-none select-none print:text-white" style={{ fontFamily: 'monospace' }}>
                        *
                    </div>
                </div>

                <div className="p-8 pb-4 pt-6 flex-1 relative">
                     {/* 2. Top Info Row - Compact */}
                     <div className="flex justify-between items-end mb-8">
                         <div className="text-xs text-zinc-600 font-medium">
                            Fecha: {getFormattedDate(date)}
                         </div>
                         <div className="text-right max-w-sm">
                             <h2 className="text-3xl font-normal text-zinc-800 mb-1">Cotización</h2>
                             <p className="text-[9px] leading-relaxed text-zinc-500 text-justify">
                                Esta cotización es válida por 30 días. {notes && notes.length > 0 ? (notes.length > 150 ? notes.slice(0, 150) + '...' : notes) : 'Gracias.'}
                             </p>
                         </div>
                     </div>


                     {/* 3. Grid Layout: Left Sidebar + Main Content */}
                     <div className="grid grid-cols-12 gap-6">
                         
                         {/* LEFT SIDEBAR (Client Info) */}
                         <div className="col-span-4 space-y-6 border-r border-zinc-200/0 pr-4"> 
                            
                            {/* CLIENTE */}
                            <div>
                                <h3 className="text-[9px] font-bold uppercase tracking-wider text-zinc-400 mb-2">Cliente</h3>
                                <p className="font-semibold text-zinc-800 text-xs mb-1">{clientName || 'Nombre del Cliente'}</p>
                                <div className="text-[10px] text-zinc-500 space-y-0.5">
                                    {clientAddress && <p>{clientAddress}</p>}
                                    {clientPhone && <p>{clientPhone}</p>}
                                    {clientEmail && <p>{clientEmail}</p>}
                                </div>
                            </div>

                            {/* FOLIO */}
                            <div>
                                <h3 className="text-[9px] font-bold uppercase tracking-wider text-zinc-400 mb-1">Folio</h3>
                                <p className="text-xs font-medium text-zinc-800">{quoteNumber}</p>
                            </div>

                            {/* PAYMENT METHOD */}
                            <div className="pt-8">
                                <h3 className="text-[9px] font-bold uppercase tracking-wider text-zinc-800 mb-2">Método de Pago:</h3>
                                {paymentMethod === 'bank' ? (
                                    <div className="text-[10px] text-zinc-500 space-y-1">
                                        <p>Banco: {bankDetails.bank}</p>
                                        <p>Cuenta: {bankDetails.account}</p>
                                        <p>CLABE: {bankDetails.clabe}</p>
                                        <p>Titular: {bankDetails.holder}</p>
                                    </div>
                                ) : (
                                    <div className="text-[10px] text-zinc-500 space-y-1">
                                        <p>Pagar en línea:</p>
                                        <a href={paymentLink} target="_blank" className="text-black underline break-all">{paymentLink}</a>
                                    </div>
                                )}
                            </div>

                            {/* CONTACT */}
                            <div className="pt-4">
                                <h3 className="text-[9px] font-bold uppercase tracking-wider text-zinc-800 mb-2">Contáctanos:</h3>
                                <div className="text-[10px] text-zinc-500 space-y-1">
                                    <p>noe.rmorales98@gmail.com</p>
                                    <p>noermorales.com</p>
                                </div>
                            </div>

                         </div>


                         {/* RIGHT MAIN CONTENT (Table) */}
                         <div className="col-span-8">
                             {/* Project Title */}
                             <div className="flex justify-between items-baseline border-b border-zinc-300 pb-2 mb-4">
                                <div className="flex gap-2 text-[9px] font-bold uppercase tracking-wider text-zinc-800">
                                    <span>Proyecto:</span>
                                    <span className="text-zinc-500">{packageName || 'GENERAL'}</span>
                                </div>
                                <div className="text-[9px] font-bold uppercase tracking-wider text-zinc-800">
                                    Factura No. {quoteNumber}
                                </div>
                             </div>

                             {/* Table Header */}
                             <div className="grid grid-cols-12 gap-2 mb-2 text-[9px] font-bold uppercase tracking-wider text-zinc-600">
                                 <div className="col-span-1 text-center">No</div>
                                 <div className="col-span-5">Descripción</div>
                                 <div className="col-span-2 text-right">Precio</div>
                                 <div className="col-span-2 text-center">Cant.</div>
                                 <div className="col-span-2 text-center">Total</div>
                             </div>

                             {/* Items */}
                             <div className="space-y-2 mb-6 min-h-[150px]">
                                {items.map((item, index) => (
                                    <div key={item.id} className="grid grid-cols-12 gap-2 text-[11px] items-center group relative py-1">
                                        {/* Highlight Bar for Total - Absolute Background */}
                                        <div className="absolute right-0 top-[-2px] bottom-[-2px] w-[16.666%] bg-[#2C2C2C] -z-10 group-hover:bg-[#3a3a3a] print:bg-[#2C2C2C]"></div>

                                        <div className="col-span-1 text-center text-zinc-500 font-light">{index + 1}</div>
                                        <div className="col-span-5 text-zinc-800 font-medium pr-2 leading-tight">
                                            {item.name || 'Servicio'}
                                        </div>
                                        <div className="col-span-2 text-right text-zinc-600">
                                            ${Number(item.price).toFixed(2)}
                                        </div>
                                        <div className="col-span-2 text-center text-zinc-600 font-light">
                                            {item.quantity}
                                        </div>
                                        <div className="col-span-2 text-center text-white font-medium z-10 px-2">
                                            ${(item.price * item.quantity).toFixed(2)}
                                        </div>
                                    </div>
                                ))}
                             </div>

                             {/* Totals Section */}
                             <div className="grid grid-cols-12 gap-2 mt-4 pt-4 border-t border-zinc-300">
                                 <div className="col-span-6">
                                     <h3 className="text-[10px] font-bold uppercase tracking-wider text-zinc-800 mb-1">Total a Pagar:</h3>
                                     <p className="text-xl font-bold text-zinc-800">${total.toFixed(2)} {currency}</p>
                                 </div>
                                 <div className="col-span-6 space-y-1">
                                     <div className="flex justify-between text-[10px] text-zinc-600 font-bold uppercase tracking-wider">
                                         <span>Subtotal</span>
                                         <span>${subtotal.toFixed(2)}</span>
                                     </div>
                                     <div className="flex justify-between text-sm text-zinc-800 font-bold uppercase tracking-wider mt-2 pt-1 border-t border-zinc-200">
                                         <span>Total</span>
                                         <span>${total.toFixed(2)}</span>
                                     </div>
                                 </div>
                             </div>

                             {/* Approved By */}
                             <div className="mt-12 text-right">
                                 <p className="text-[9px] font-bold uppercase tracking-wider text-zinc-600 mb-6">Aprobado Por</p>
                                 <div className="inline-block relative">
                                     {/* Signature Placeholder */}
                                     <div className="h-12 w-28 mx-auto border-b border-zinc-800 mb-1">
                                          {/* You could add a signature image here if uploaded */}
                                          <div className="w-full h-full flex items-end justify-center pb-1 opacity-50 font-handwriting italic text-xl">
                                            Noelí R.
                                          </div>
                                     </div>
                                     <p className="font-bold text-xs text-zinc-800">NOELÍ RODRÍGUEZ</p>
                                     <p className="text-[9px] text-zinc-500">@noermorales</p>
                                 </div>
                             </div>

                         </div>
                     </div>
                </div>

                {/* Print Margin Fix */}
                <div className="hidden print:block h-8 w-full p-4 text-center text-[8px] text-zinc-300">
                    noermorales.com
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
